name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install build backend
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build distribution artifacts
        run: python -m build

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
